

a=100000
b="uttarakhand"
c="delhi"
d=1000000
e="modi"
f=10000000
question=[" full form of UK-","capital of India?","P.M of India?"]
q2=["capital of India?"]
q3=["P.M of India?"]

for i in question:
    

    if(input(i)==b):
        print("right answer,you have win",a,)
        print("next question is on your screan")
      
    else:
        print("wrong answer,so you can go home.") 
    break 
for k in q2:
    if(input(k)==c):
        print("right answer,you have win",(a+d),"\n next question on your screan-")
    else:
        print("wrong answer,so you can go home.")
        break
for p in q3:
    if(input(p)==e):
        print("right answer,you have win",(a+d+f))
    else:
        print("wrong answer,so you can go home.you won ",(a+b))
    print("thanks")
    if(input(i)==c):
        print("right answer,you have win",(a+d))
    else:
        print("wrong answer,now you can go home.you just won",a)
    ask=input(question())
a=10000
b=100000
c=10000000
# def win(price):
g=("right answer you have win",a,"next question on your screan")
question=["queen of hills-","father of the nation-","PM of India-"]
answer=["Mussoorie","Gandhi","Modi"]
for i in question:

    if(input(i)==answer):
     print(g)   
    else:
        ("wrong answer you will go to home. ")
        


   

